# Generated by Django 4.2.30 on 2026-07-04 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('concurrency', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('online', 'Online'), ('draining', 'Draining'), ('offline', 'Offline')], default='online', max_length=32)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='workers.worker')),
            ],
            options={
                'ordering': ['-seen_at'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['status', 'last_heartbeat'], name='workers_wor_status_353aa0_idx'),
        ),
    ]
