# Generated by Django 4.2.30 on 2026-07-04 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retry', '0001_initial'),
        ('jobs', '0001_initial'),
        ('workers', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], db_index=True, default='INFO', max_length=16)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('message', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='jobs.job')),
                ('retry_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='retry.retryattempt')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='scheduling.schedule')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='workers.worker')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'event_type', 'timestamp'], name='logs_logent_level_7c21d6_idx')],
            },
        ),
    ]
