# Generated by Django 4.2.30 on 2026-07-04 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('policy_type', models.CharField(choices=[('fixed', 'Fixed'), ('linear', 'Linear'), ('exponential', 'Exponential')], max_length=32)),
                ('initial_delay_seconds', models.IntegerField(default=60)),
                ('backoff_factor', models.FloatField(default=2.0)),
                ('max_retries', models.IntegerField(default=3)),
                ('jitter', models.BooleanField(default=False)),
                ('conditions', models.JSONField(blank=True, help_text='Optional conditions to trigger retry (e.g., HTTP status codes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('attempted', 'Attempted'), ('failed', 'Failed'), ('succeeded', 'Succeeded')], max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_attempts', to='jobs.job')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retry.retrypolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
